/**
 * PtyManager — manages the lifecycle of all pseudoterminal (PTY) instances.
 *
 * Each terminal session gets a node-pty process spawned with the project's
 * working directory. Data from PTY stdout is forwarded to the renderer via IPC.
 */

import { BrowserWindow } from 'electron'
import * as pty from 'node-pty'
import { IPC } from '../shared/types'

/** Returns the default shell for the current platform. */
function getDefaultShell(): string {
  if (process.platform === 'win32') return 'powershell.exe'
  return process.env.SHELL || '/bin/zsh'
}

export class PtyManager {
  private ptys = new Map<string, pty.IPty>()
  private window: BrowserWindow | null = null

  /** Bind the manager to a BrowserWindow so it can send IPC events. */
  setWindow(window: BrowserWindow): void {
    this.window = window
  }

  /**
   * Spawn a new PTY process.
   * @param id - Unique terminal session ID (generated by the renderer).
   * @param cwd - The working directory for the shell (project path).
   * @param cols - Initial terminal columns.
   * @param rows - Initial terminal rows.
   */
  spawn(id: string, cwd: string, cols: number, rows: number): void {
    const shell = getDefaultShell()

    try {
      const proc = pty.spawn(shell, [], {
        name: 'xterm-256color',
        cols,
        rows,
        cwd,
        env: {
          ...process.env,
          TERM: 'xterm-256color',
          COLORTERM: 'truecolor'
        } as Record<string, string>
      })

      // Forward PTY output to the renderer.
      proc.onData((data) => {
        this.window?.webContents.send(IPC.PTY_DATA, { id, data })
      })

      this.ptys.set(id, proc)

      // Notify the renderer when the PTY exits.
      // Guard: only act if this proc is still the current one for this ID,
      // otherwise a restart has already replaced it with a new instance.
      proc.onExit(({ exitCode }) => {
        if (this.ptys.get(id) === proc) {
          this.window?.webContents.send(IPC.PTY_EXIT, { id, exitCode })
          this.ptys.delete(id)
        }
      })
    } catch (err) {
      // Spawn failed (e.g. invalid cwd). Write the error into the terminal
      // and immediately signal exit so the UI updates.
      const message = err instanceof Error ? err.message : String(err)
      this.window?.webContents.send(IPC.PTY_DATA, {
        id,
        data: `\r\nFailed to spawn shell: ${message}\r\n`
      })
      this.window?.webContents.send(IPC.PTY_EXIT, { id, exitCode: 1 })
    }
  }

  /** Write data (keystrokes) to a specific PTY. */
  write(id: string, data: string): void {
    this.ptys.get(id)?.write(data)
  }

  /** Resize a specific PTY to match the xterm.js dimensions. */
  resize(id: string, cols: number, rows: number): void {
    try {
      this.ptys.get(id)?.resize(cols, rows)
    } catch {
      // PTY may have already exited — safe to ignore.
    }
  }

  /** Kill a specific PTY process. */
  kill(id: string): void {
    const proc = this.ptys.get(id)
    if (proc) {
      proc.kill()
      this.ptys.delete(id)
    }
  }

  /** Emergency kill — terminate all running PTY processes. */
  killAll(): void {
    for (const [id, proc] of this.ptys) {
      proc.kill()
      this.ptys.delete(id)
    }
  }

  /** Returns the count of currently alive PTY processes. */
  get activeCount(): number {
    return this.ptys.size
  }
}
